branches:
  only:
    - develop
    - master

image:
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013

environment:
  matrix:
    - SCRIPT: ci_boost_status
    - SCRIPT: ci_boost_status
      TARGET: quick
    - SCRIPT: ci_boost_test_library

init:
  - cd %APPVEYOR_BUILD_FOLDER%/..
  - appveyor DownloadFile "https://raw.githubusercontent.com/boostorg/release-tools/develop/ci_boost_common.py"
  - appveyor DownloadFile "https://raw.githubusercontent.com/boostorg/release-tools/develop/%SCRIPT%.py"
  - cd %APPVEYOR_BUILD_FOLDER%
install: python ../%SCRIPT%.py install
before_build: python ../%SCRIPT%.py before_build
build_script: python ../%SCRIPT%.py build_script
after_build: python ../%SCRIPT%.py after_build
before_test: python ../%SCRIPT%.py before_test
test_script: python ../%SCRIPT%.py test_script
after_test: python ../%SCRIPT%.py after_test
on_success: python ../%SCRIPT%.py on_success
on_failure: python ../%SCRIPT%.py on_failure
on_finish: python ../%SCRIPT%.py on_finish
